image: codefresh/slack-message-sender
version: 0.1.0
description: Send message to slack channel
keywords:
  - slack
home: https://github.com/codefresh-io/slack-message-sender
sources:
  - https://github.com/codefresh-io/slack-message-sender
maintainers: # (optional)
  - name: Oleg Sucharevich
    email: olegs@codefresh.io
icon: https://upload.wikimedia.org/wikipedia/commons/7/76/Slack_Icon.png
envs:
  - name: WEBHOOK_URL
    type: required
    description: Url to the channel
  - name: SLACK_MESSAGE
    type: required
    description: Message to send
  - name: DEBUG
    description: print verbose install output